import Head from 'next/head';
import Layout from '../components/Layout';
import PostCard from '../components/PostCard';

const posts = [
  {
    id: '1',
    title: 'ola mundo',
    description:
      '  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacus quam, fringilla vel mauris auctor, ullamcorper cursus metus. Praesent a ante ultricies nunc efficitur vehicula non ut nulla.  ',
    thumbnail:
      'http://www.mdtop.com.br/wp-content/uploads/2021/01/placeholder-images-image_large.png',
  },
  {
    id: '2',
    title: 'ola mundo',
    description:
      '  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacus quam, fringilla vel mauris auctor, ullamcorper cursus metus. Praesent a ante ultricies nunc efficitur vehicula non ut nulla.  ',
    thumbnail:
      'http://www.mdtop.com.br/wp-content/uploads/2021/01/placeholder-images-image_large.png',
  },
  {
    id: '3',
    title: 'ola mundo',
    description:
      '  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacus quam, fringilla vel mauris auctor, ullamcorper cursus metus. Praesent a ante ultricies nunc efficitur vehicula non ut nulla.  ',
    thumbnail:
      'http://www.mdtop.com.br/wp-content/uploads/2021/01/placeholder-images-image_large.png',
  },
  {
    id: '4',
    title: 'ola mundo',
    description:
      '  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacus quam, fringilla vel mauris auctor, ullamcorper cursus metus. Praesent a ante ultricies nunc efficitur vehicula non ut nulla.  ',
    thumbnail:
      'http://www.mdtop.com.br/wp-content/uploads/2021/01/placeholder-images-image_large.png',
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>News | Coders Club</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='w-4/5 m-auto bg-white mt-[-42px] rounded-tl-[1.875rem] min-h-[21.5rem] p-6 md:p=14 flex flex-wrap-reverse  justify-around'>
        <div className='w-[38.75rem] max-h-80 '>
          <h2 className='font-bold text-[#232323] text-2xl mb-[0.625rem'>
            asdasd
          </h2>
          <p className='text-lg'>asdasdasd</p>
        </div>

        <div className='w-[35.625rem] max-h-80'>
          <img
            src='http://www.mdtop.com.br/wp-content/uploads/2021/01/placeholder-images-image_large.png'
            className='w-full h-full object-cover rounded-[1.25rem]'
          />
        </div>
      </div>

      <div className='max-w-[80%] m-auto flex gap-16 flex-wrap justify-center'>
        {posts.map((post) => (
          <PostCard key={post.id} post={post} />
        ))}
      </div>
    </div>
  );
}

Home.getLayout = function getlayout(page) {
  return <Layout title={'News'}>{page}</Layout>;
};
